title: COURSE TITLE # title which appears for the website
email: sarazm.2000@gmail.com
description: > # short discription of your website. It is helpful for making your website more discoverable and appears while previewing your website.
    A jekyll template for creating course websites.
 
baseurl: "orca_web_template"   # specify the subpath of your site
url: "https://linear-algebra-sut.github.io" # the base hostname & protocol for YOUR site, e.g. http://example.com
twitter_username: #
github_username: #
theme: minima
plugins:
  - jekyll-feed
